const C = {
  AUTHENTICATED: 'AUTHENTICATED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  LOGIN_REQUESTING: 'LOGIN_REQUESTING',
  LOGIN_SUCCESS: 'LOGIN_SUCCES',
  LOGIN_ERROR: 'LOGIN_ERROR',
  GET_POKEMON_REQUEST: 'GET_POKEMON_REQUEST',
  GET_POKEMON_SUCCESS: 'GET_POKEMON_SUCCESS',
  GET_POKEMON_ERROR: 'GET_POKEMON_ERROR',
  GET_POKEMON_UPDATE: 'GET_POKEMON_UPDATE',
  POST_POKEMON_LIKE_REQUEST: 'POST_POKEMON_LIKE_REQUEST',
  POST_POKEMON_LIKE_SUCCESS: 'POST_POKEMON_LIKE_SUCCESS',
  POST_POKEMON_LIKE_ERROR: 'POST_POKEMON_LIKE_ERROR',
  GET_POKEMON_FAV_REQUEST: 'GET_POKEMON_FAV_REQUEST',
  GET_POKEMON_FAV_SUCCESS: 'GET_POKEMON_FAV_SUCCESS',
  GET_POKEMON_FAV_ERROR: 'GET_POKEMON_FAV_ERROR',
  GET_POKEMON_FAV_UPDATE: 'GET_POKEMON_FAV_UPDATE'
}

export default C;
