const C = {
  AUTHENTICATED: 'AUTHENTICATED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  LOGIN_REQUESTING: 'LOGIN_REQUESTING',
  LOGIN_SUCCESS: 'LOGIN_SUCCES',
  LOGIN_ERROR: 'LOGIN_ERROR',
  GET_POKEMON_REQUEST: 'GET_POKEMON_REQUEST',
  GET_POKEMON_SUCCESS: 'GET_POKEMON_SUCCESS',
  GET_POKEMON_ERROR: 'GET_POKEMON_ERROR'
}

export default C;
