const C = {
  AUTHENTICATED: 'AUTHENTICATED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  LOGIN_REQUESTING: 'LOGIN_REQUESTING',
  LOGIN_SUCCESS: 'LOGIN_SUCCES',
  LOGIN_ERROR: 'LOGIN_ERROR',
}

export default C;
